# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7z010clg225-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.cache/wt [current_project]
set_property parent.project_path /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part trenz.biz:te0726_02m:part0:1.2 [current_project]
add_files /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/bd/Lab5/Lab5.bd
set_property used_in_implementation false [get_files -all /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/bd/Lab5/ip/Lab5_processing_system7_0_0/Lab5_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/bd/Lab5/Lab5_ooc.xdc]
set_property is_locked true [get_files /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/bd/Lab5/Lab5.bd]

read_vhdl -library xil_defaultlib {
  /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/new/Debounce.vhd
  /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/new/ClockInverter.vhd
  /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/sources_1/bd/Lab5/hdl/Lab5_wrapper.vhd
}
foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/constrs_1/new/user_consraints.xdc
set_property used_in_implementation false [get_files /home/exchizz/SDU/Skole/7.Semester/EMB1/VHDL/EMB_group_4/Lab5/Lab5.srcs/constrs_1/new/user_consraints.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top Lab5_wrapper -part xc7z010clg225-1


write_checkpoint -force -noxdef Lab5_wrapper.dcp

catch { report_utilization -file Lab5_wrapper_utilization_synth.rpt -pb Lab5_wrapper_utilization_synth.pb }
