set_property IOSTANDARD LVCMOS33 [get_ports pwm_out]
set_property PACKAGE_PIN P15 [get_ports pwm_out]

set_property PACKAGE_PIN N14 [get_ports in_a]
set_property PACKAGE_PIN L14 [get_ports in_b]
set_property IOSTANDARD LVCMOS33 [get_ports in_b]
set_property IOSTANDARD LVCMOS33 [get_ports in_a]

set_property IOSTANDARD LVCMOS33 [get_ports {outputz[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[0]}]
set_property PACKAGE_PIN R15 [get_ports {outputz[7]}]
set_property PACKAGE_PIN R13 [get_ports {outputz[6]}]
set_property PACKAGE_PIN R12 [get_ports {outputz[5]}]
set_property PACKAGE_PIN L12 [get_ports {outputz[4]}]
set_property PACKAGE_PIN M15 [get_ports {outputz[3]}]
set_property PACKAGE_PIN L13 [get_ports {outputz[2]}]
set_property PACKAGE_PIN M14 [get_ports {outputz[1]}]
set_property PACKAGE_PIN P15 [get_ports {outputz[0]}]
