set_property IOSTANDARD LVCMOS33 [get_ports pwm_out]
set_property PACKAGE_PIN M12 [get_ports pwm_out]

set_property PACKAGE_PIN N14 [get_ports in_a]
set_property PACKAGE_PIN L14 [get_ports in_b]
set_property IOSTANDARD LVCMOS33 [get_ports in_b]
set_property IOSTANDARD LVCMOS33 [get_ports in_a]

set_property IOSTANDARD LVCMOS33 [get_ports {outputz[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {outputz[0]}]
set_property PACKAGE_PIN R15 [get_ports {outputz[7]}]
set_property PACKAGE_PIN R13 [get_ports {outputz[6]}]
set_property PACKAGE_PIN R12 [get_ports {outputz[5]}]
set_property PACKAGE_PIN L12 [get_ports {outputz[4]}]
set_property PACKAGE_PIN M15 [get_ports {outputz[3]}]
set_property PACKAGE_PIN L13 [get_ports {outputz[2]}]
set_property PACKAGE_PIN M14 [get_ports {outputz[1]}]
set_property PACKAGE_PIN P15 [get_ports {outputz[0]}]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list design_1_i/processing_system7_0/inst/FCLK_CLK1]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 1 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list design_1_i/debounce_0_outz]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK1]
